version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    networks:
      - employee-mysql
    environment:
      MYSQL_DATABASE: FABER_EXTRACT
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
      
  maven:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8181:8088
    restart: always
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
volumes:
  db-data:
  
networks:
  employee-mysql: 