version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    networks:
      - employee-mysql
    environment:
      MYSQL_DATABASE: FABER_EXTRACT
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
      
  maven:
    image: maven:3.5-jdk-8
    ports:
      - 8181:8088
    restart: always
    working_dir: /
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    command: mvn clean spring-boot:run
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
volumes:
  db-data:
  
networks:
  employee-mysql: 